edit: set interface object to interact with the sidebar
	The inferface for the satellite defined in sat_data_intf is being used
	to hold data within the Sidebar component.

	ERROR: TypeScript for some reason in line 31 of Sidebar.ts want to
	typecheck the interface when being added to the list.